name: C Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build Project
        run: make

      - name: Run Test Binary
        run: ./build/ton_demo
